name: Build rules.dat
on:
  push:
    branches:
      - bpg
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/go.mod

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash

      - name: Build rules.dat file
        run: |
          cd code || exit 1
          go run ./ --data ./data --out ./rules.dat

      - name: Generate rules.dat sha256 hash
        run: |
          cd code || exit 1
          sha256sum rules.dat > rules.dat.sha256sum

      - name: Generate Zip
        run: |
          cd code || exit 1
          zip -9 rules.dat.zip rules.dat
          sha256sum rules.dat.zip > rules.dat.zip.sha256sum

      - name: Release and upload assets
        run: |
          cd code || exit 1
          gh release create ${{ env.TAG_NAME }} --generate-notes --latest --title ${{ env.RELEASE_NAME }} ./rules.dat ./rules.dat.*
          cd ../ && rm -rf code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
