name: Build dlc.dat
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
  pull_request:
    types: [synchronize]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
        shell: bash
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/go.mod

      - name: Build rules.dat file & Set variables
        run: go run ./

      - name: Release and upload assets
        run: gh release create $(date +%Y%m%d%H%M%S) --generate-notes --latest --title $(date +%Y%m%d%H%M%S) rules.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bad-proxy-go
          path: rules.dat
          overwrite: true
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'rules.dat'